'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Button } from '@/components/ui/button'

const nav = [
  ['home', 'Home'], ['learn', 'Learn'], ['build', 'Build'], ['ambassadors', 'Ambassadors'], ['security', 'Teams'], ['events', 'Events'], ['community', 'Community'],
]

const pageTheme = { home: 'cream', learn: 'yellow', courses: 'course', build: 'night', ambassadors: 'clay', security: 'forest', events: 'coral', community: 'violet' }

function path(id) { return id === 'home' ? '/' : `/${id}` }

function Arrow() { return <span aria-hidden="true">↗</span> }

function Eyebrow({ children, tone = '' }) { return <p className={`eyebrow ${tone}`}><i />{children}</p> }

function AdinkraSymbol({ kind = 'gye-nyame', label = 'Adinkra symbol' }) {
  const path = kind === 'sankofa' ? 'M52 21c-15 0-25 10-25 23 0 8 5 14 13 16-4-7-2-14 5-18 4-2 8-6 7-12 7 3 10 8 9 14' : kind === 'nkyinkyim' ? 'M22 25h14l-7 15h14l-7 15h22' : 'M40 16c-9 8-15 14-15 24 0 13 10 24 23 24 9 0 16-5 20-12-9 5-18 1-18-8 0-8 8-13 17-10-3-10-11-18-27-18Z'
  return <span className={`adinkra adinkra-${kind}`} role="img" aria-label={label}><svg viewBox="0 0 80 80" aria-hidden="true"><circle cx="40" cy="40" r="31" /><path d={path} /></svg></span>
}

function OrbitMark({ small = false }) {
  return <div className={`orbit-mark ${small ? 'small' : ''}`} aria-hidden="true">
    <span className="orbit-ring one" /><span className="orbit-ring two" /><span className="orbit-core" />
  </div>
}

function Header({ page, open, setOpen }) {
  return <header className={`site-header ${pageTheme[page]}`}>
    <Link href="/" className="brand" aria-label="Solana Ghana home">
      <img src="/solana_ghana.jpeg" alt="Solana Ghana Community" />
      <span>Solana<br />Ghana</span>
    </Link>
    <nav className={open ? 'nav-links open' : 'nav-links'} aria-label="Primary navigation">
      {nav.map(([id, label]) => <Link key={id} href={path(id)} className={id === page ? 'active' : ''} onClick={() => setOpen(false)}>{label}</Link>)}
    </nav>
    <a className="header-join" href="https://t.me/solanaghanacommunity" target="_blank" rel="noreferrer">Join us <Arrow /></a>
    <button className="menu-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle menu"><span /><span /></button>
  </header>
}

function Footer() {
  return <footer className="footer">
    <div><Eyebrow tone="light">Independent initiative</Eyebrow><h2>Build Ghana’s<br /><em>on-ramp.</em></h2></div>
    <div className="footer-links"><div><b>Explore</b><Link href="/learn">Learn</Link><Link href="/build">Build</Link><Link href="/security">Teams</Link></div><div><b>Connect</b><a href="https://t.me/solanaghanacommunity" target="_blank" rel="noreferrer">Telegram</a><a href="https://chat.whatsapp.com/JTaWqtd3YK78ZMHhChc9Z5?mode=gi_t" target="_blank" rel="noreferrer">WhatsApp</a><a href="#join">GitHub</a></div></div>
    <div className="footer-base">© 2026 Solana Ghana Community <span>Not an official Superteam or Solana Foundation chapter.</span></div>
  </footer>
}

function Signup({ tone = 'dark' }) {
  const [sent, setSent] = useState(false)
  return <form className={`signup ${tone}`} onSubmit={(event) => { event.preventDefault(); setSent(true) }}>
    <label htmlFor={`email-${tone}`}>Get the first invite</label>
    <div><input id={`email-${tone}`} required type="email" placeholder="you@example.com" aria-label="Email address" /><Button variant={tone === 'dark' ? 'lime' : 'ink'} type="submit">{sent ? 'You’re in' : 'Keep me posted'} <Arrow /></Button></div>
    <small>{sent ? 'Thank you — we’ll be in touch when the founding cohort opens.' : 'Founding cohort updates only. No noise.'}</small>
  </form>
}

function Home() {
  return <main className="home-page">
    <section className="home-hero"><div className="hero-grid" /><AdinkraSymbol kind="gye-nyame" label="Gye Nyame symbol" />
      <div className="hero-copy reveal-up"><Eyebrow>Solana Ghana Community</Eyebrow><h1>Akwaaba<span>.</span></h1><p className="hero-lede">The gateway for Ghanaian builders to learn, build, and reach the Solana ecosystem.</p><div className="hero-actions"><Button asChild><Link href="/community">Join the founding cohort <Arrow /></Link></Button><Link className="text-link" href="/learn">See how it works <Arrow /></Link></div></div>
      <div className="hero-note">Twi for <b>welcome</b> <span>⌁</span> From Ghana, into the network.</div>
      <div className="flag-line"><i /><i /><i /></div>
    </section>
    <section className="numbers wrap" aria-label="Community targets"><div><strong className="metric-value">4</strong><span className="metric-label">founders organizing</span></div><div><strong className="metric-value">1+</strong><span className="metric-label">university to begin</span></div><div><strong className="metric-value">30+</strong><span className="metric-label">Q1 member target</span></div><div><strong className="metric-value">$200</strong><span className="metric-label">self-funded start</span></div></section>
    <section className="infrastructure wrap"><div className="section-intro"><Eyebrow>Our point of view</Eyebrow><h2>Not an event.<br /><em>Infrastructure.</em></h2><p>We are building the local systems that turn curiosity into contribution—not a one-off meetup calendar.</p></div><div className="infrastructure-grid"><article><b>01</b><h3>Talent pipeline</h3><p>Campus introductions, practical workshops, contribution tasks, build sprints and pathways into work.</p></article><article><b>02</b><h3>Safe by default</h3><p>Security review culture, wallet safety and transparent developer assurance from day one.</p></article><article><b>03</b><h3>Local problems</h3><p>Build prompts rooted in merchant workflows, remittances and Ghanaian payment realities.</p></article><article><b>04</b><h3>Public receipts</h3><p>Open curriculum, Speed Test data and visible builder outcomes to earn every next step.</p></article></div></section>
    <section className="chainpay wrap"><div className="chainpay-image"><img src="/solana_ghana_project.jpeg" alt="ChainPay x402" /><span>First project shipped</span></div><div className="chainpay-copy"><Eyebrow tone="lime">Featured build</Eyebrow><h2>Proof lives<br />in the work.</h2><p>ChainPay is a live Devnet payment project from the founding ecosystem—a concrete starting point for the builders we want to grow.</p><Button variant="lime" asChild><a href="https://chainpay-frontend.onrender.com" target="_blank" rel="noreferrer">Open ChainPay <Arrow /></a></Button><small>Live on Devnet · explore the interface</small></div></section>
    <section className="event-teaser wrap"><div className="section-intro"><Eyebrow>First quarter</Eyebrow><h2>Come with<br />your questions.</h2></div><div className="event-list">{[['01','Akwaaba Genesis Meetup','Meet the vision. Meet the people. Help form the first cohort.'],['02','Faucet & Wallet Build Night','Hands-on contributions to shared onboarding tools.'],['03','Africa Solana Speed Test','Create the first public dataset from Ghanaian connections.']].map(([n,t,d]) => <article key={n}><b>{n}</b><div><h3>{t}</h3><p>{d}</p></div><Link href="/events" aria-label={`Read about ${t}`}><Arrow /></Link></article>)}</div></section>
    <section className="home-join" id="join"><OrbitMark /><div><Eyebrow tone="light">The beginning is small</Eyebrow><h2>Make your first<br /><em>useful move.</em></h2></div><Signup /></section>
  </main>
}

function Learn() {
  const modules = [['01','Rust foundations','Get comfortable with the language underneath durable Solana programs.'],['02','Solana essentials','Learn accounts, transactions, PDAs and the network model through practice.'],['03','Anchor workshop','Move from concepts into programs, tests and a real build workflow.'],['04','Capstone','Ship a localnet vault or escrow project worth showing in a portfolio.']]
  return <main className="learn-page"><section className="learn-hero wrap"><AdinkraSymbol kind="nkyinkyim" label="Nkyinkyim symbol" /><div><Eyebrow>Learning that ends in making</Eyebrow><h1>Start where<br />the work gets <em>real.</em></h1><p>A structured, self-paced Rust-to-Solana path for the first Ghanaian cohort—made for beginners with ambition, not spectators.</p><Button asChild><Link href="/courses">Explore the course <Arrow /></Link></Button></div><div className="book-stack" aria-hidden="true"><div className="book b1">RUST</div><div className="book b2">SOLANA</div><div className="book b3">SHIP IT</div><OrbitMark /></div></section>
    <section className="course-wrap"><div className="wrap"><Eyebrow>Solana Core Course</Eyebrow><div className="course-header"><h2>Four moves.<br /><em>One capability.</em></h2><p>Our curriculum is already open-source and designed to turn learning into an artifact: a working capstone and a visible contribution trail.</p></div><div className="module-grid">{modules.map(([n,t,d]) => <article key={n}><b>{n}</b><div className="module-icon">✦</div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
    <section className="ambassador wrap"><div className="ambassador-tag">Campus<br />to<br />community</div><div><Eyebrow>Ambassador programme</Eyebrow><h2>A lead in every room that matters.</h2><p>We begin with Wisconsin Ghana University, equipping a named student lead with curriculum, presentation material, a dedicated community role and a direct line to the core team.</p><div className="pill-list"><span>Run monthly meetups</span><span>Recruit builders</span><span>Surface local projects</span><span>Represent campus at demo day</span></div></div></section>
    <section className="partners wrap"><Eyebrow>First campus cells</Eyebrow><div><h2>Built to outlast<br />a single event.</h2><div className="partner-list"><article><b>01</b><h3>Wisconsin Ghana University</h3><span className="status live">Active outreach</span></article><article><b>02</b><h3>Next partner</h3><span className="status">To be confirmed</span></article><article><b>03</b><h3>Next partner</h3><span className="status">To be confirmed</span></article></div></div></section><section className="learn-cta"><h2>Don’t just<br />collect links.</h2><Link href="/community">Join the learning cohort <Arrow /></Link></section></main>
}

function Build() {
  const projects = [['ChainPay','Live on Devnet','Transparent payment flows, receipts and builder-facing infrastructure.','live'],['Akwaaba Faucet','In development','A shared first contribution surface: onboarding, verification and wallet support.','build'],['Africa Speed Test','Planning','Open measurement data on Solana performance from Ghanaian connections.','plan'],['Payments Sandbox','Research concept','A controlled prototype environment for merchant workflow research.','concept']]
  const learning = ['Beginner', 'Rust', 'Anchor', 'Frontend', 'Solana programs', 'DeFi', 'AI × Solana', 'Agentic payments']
  const opportunities = ['Grants', 'Hackathons', 'Bounties', 'Jobs', 'Fellowships', 'Ambassador programs']
  const bountyGroups = [['Active bounties', 'No active bounties published yet.'], ['Community bounties', 'Community bounty board is being prepared.'], ['Past bounties', 'No completed bounties yet.']]
  return <main className="build-page"><section className="build-hero wrap"><AdinkraSymbol kind="sankofa" label="Sankofa symbol" /><div><Eyebrow tone="lime">Builder cloud</Eyebrow><h1>Make a dent<br />in the <em>real.</em></h1><p>We start with useful systems, Ghanaian questions and artifacts that have somewhere to go after demo day.</p><Button variant="lime" asChild><Link href="/community">Find a build lane <Arrow /></Link></Button></div><div className="dimension" aria-hidden="true"><div className="cube"><i /><i /><i /><i /><i /><i /></div><div className="dimension-copy">BUILD<br /><span>LOCALLY</span></div></div><nav className="build-subnav" aria-label="Build page sections"><a href="#projects">Projects</a><a href="#learning-hub">Learning hub</a><a href="#opportunities-hub">Opportunities</a><a href="#bounties">Bounties</a></nav></section>
    <section className="project-shelf wrap" id="projects"><div className="shelf-title"><Eyebrow tone="lime">Work in view</Eyebrow><h2>Current<br />signals.</h2></div><div className="project-grid">{projects.map(([t,s,d,k], index) => <article className={`project ${k}`} key={t}><div className="project-number">0{index + 1}</div>{k === 'live' && <img src="/solana_ghana_project.jpeg" alt="ChainPay x402" />}<span className="project-status">{s}</span><h3>{t}</h3><p>{d}</p>{k === 'live' ? <a href="https://chainpay-frontend.onrender.com" target="_blank" rel="noreferrer">View project <Arrow /></a> : <Link href="/community">Contribute <Arrow /></Link>}</article>)}</div></section>
    <section className="build-hubs wrap"><div className="build-hub" id="learning-hub"><Eyebrow tone="lime">Learning hub</Eyebrow><h2>Learn by<br /><em>building.</em></h2><p>Resources organised around the skills that let a new builder become useful quickly.</p><div className="build-hub-list">{learning.map((item, index) => <Link href="/learn" key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span><Arrow /></Link>)}</div></div><div className="build-hub opportunities" id="opportunities-hub"><Eyebrow tone="lime">Opportunities hub</Eyebrow><h2>Turn skill into<br /><em>a next step.</em></h2><p>Verified calls and pathways will appear here as they are confirmed—without inflated claims or stale listings.</p><div className="build-hub-list">{opportunities.map((item, index) => <Link href={item === 'Bounties' ? '#bounties' : item === 'Ambassador programs' ? '/ambassadors' : '/community'} key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span><Arrow /></Link>)}</div></div></section>
    <section className="build-bounties" id="bounties"><div className="wrap"><div className="build-bounties-intro"><div><Eyebrow tone="lime">Bounty board</Eyebrow><h2>Earn by making<br /><em>useful things.</em></h2></div><p>A single, honest place for Ghanaian builders to find ecosystem work, contribute visibly, and earn when verified opportunities are available.</p></div><div className="build-bounty-grid">{bountyGroups.map(([title, empty]) => <article key={title}><Eyebrow tone="lime">{title}</Eyebrow><h3>{title}</h3><p>{title === 'Active bounties' ? 'Open opportunities will appear here when verified. We will not invent rewards, deadlines, or ecosystem partnerships.' : 'Tasks created for useful, reviewable public work with clear terms and visible receipts.'}</p><strong>{empty}</strong><small>Published bounties will show reward, deadline, difficulty, skills and a clear apply or submit action.</small></article>)}</div><div className="build-bounty-actions"><Link href="/community">Post a bounty <Arrow /></Link><Link href="/community">Submit completed work <Arrow /></Link></div></div></section>
    <section className="sandbox"><div className="wrap sandbox-inner"><div><Eyebrow tone="lime">Flagship experiment</Eyebrow><h2>Payments, without the hand-waving.</h2><p>The Ghana Stablecoin Payments & Commerce Sandbox is deliberately a controlled prototype and research environment—not a real-money pilot, on/off-ramp or custody product.</p></div><div className="sandbox-orbit"><span>Merchant payments</span><span>Payment links</span><span>Receipts</span><span>Refunds</span><span>Reconciliation</span><i /></div></div></section><section className="build-cta"><p>Have a useful contribution?</p><Link href="/community">Bring it into the room <Arrow /></Link></section></main>
}

function Courses() {
  const rustlings = ['Mutable bindings', 'Ownership and borrowing', 'Enums, match, Result and ?', 'Slices and zero-copy parsing', 'Structs, traits and generics', 'Collections, iterators and lifetimes', 'Checked arithmetic']
  const anchor = ['Account as state', 'Program vs account', 'PDA determinism', 'CPI router', 'Signer, owner and mutability checks', 'Confidential-transfer flow']
  const protocol = ['Fixed-point and economic modelling', 'Oracle confidence and stale-price checks', 'MEV and ordering', 'CPI and cross-program security', 'Upgrade authority and governance', 'Deployment, operations and review', 'Fuzz testing, ZK and optimisation']
  return <main className="courses-page"><section className="courses-hero"><div className="wrap"><Eyebrow>rssol-memory curriculum</Eyebrow><div className="courses-hero-grid"><div><h1>Learn the<br /><em>reasoning</em><br />before the framework.</h1><p>A test-driven Rust-to-Solana course that asks you to predict the state transition, write the smallest correct fix, and prove it with tests.</p><div className="courses-actions"><Button asChild><a href="https://github.com/stawuah/rssol-memory/blob/main/README.md" target="_blank" rel="noreferrer">Open the repository <Arrow /></a></Button><a href="#rustlings-core" className="text-link">Start with Rustlings <Arrow /></a></div></div><div className="course-principle"><span>01</span><strong>Read the test<br />before the code.</strong><p>The compiler and the test suite are part of the lesson—not obstacles between you and an answer.</p></div></div><nav className="course-nav" aria-label="Course tracks"><a href="#rustlings-core"><b>01</b> Rustlings Core</a><a href="#anchor-core"><b>02</b> Anchor Core</a><a href="#protocol-core"><b>03</b> Protocol Core</a></nav></div></section>
    <section className="course-track rustlings" id="rustlings-core"><div className="wrap course-track-grid"><div className="track-sticky"><Eyebrow>Track 01 · before Anchor</Eyebrow><span className="track-kicker">RUSTLINGS</span><h2>Make Rust<br />feel <em>mechanical.</em></h2><p>Learn how Rust controls data access so ownership, borrowing and state transitions stop feeling like guesses.</p><a href="https://github.com/stawuah/rssol-memory/tree/main/rustlings-core" target="_blank" rel="noreferrer">View Rustlings Core <Arrow /></a></div><div className="track-content"><div className="study-note"><b>Study loop</b><span>Open one exercise → read the test → predict → replace <code>todo!()</code> → run <code>cargo test --workspace</code>.</span></div><ol>{rustlings.map((item, index) => <li key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span><i>↘</i></li>)}</ol><aside><strong>Why this comes first</strong><p>Anchor programs are Rust state machines with account validation. When you can reason about ownership and state transitions, Anchor becomes a thin layer instead of a wall.</p></aside></div></div></section>
    <section className="course-track anchor" id="anchor-core"><div className="wrap course-track-grid"><div className="track-sticky"><Eyebrow>Track 02 · Solana by analogy</Eyebrow><span className="track-kicker">ANCHOR</span><h2>Turn lockers<br />into <em>state.</em></h2><p>Move from Rust fundamentals into accounts, PDAs, programs and constraints—one explicit state transition at a time.</p><a href="https://github.com/stawuah/rssol-memory/tree/main/anchor-core" target="_blank" rel="noreferrer">View Anchor Core <Arrow /></a></div><div className="track-content"><div className="study-note"><b>Mental model</b><span>An account is a locker. A program is the machine that can change it. An instruction is a request. A PDA is a locker with no private key.</span></div><ol>{anchor.map((item, index) => <li key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span><i>↘</i></li>)}</ol><aside><strong>Capstone caution</strong><p>Confidential transfers can hide amounts. They do not automatically hide timing, intent, routing structure or failed attempt patterns.</p></aside></div></div></section>
    <section className="course-track protocol" id="protocol-core"><div className="wrap course-track-grid"><div className="track-sticky"><Eyebrow>Track 03 · production engineering</Eyebrow><span className="track-kicker">PROTOCOL</span><h2>Build around<br /><em>invariants.</em></h2><p>Learn the financial, security and operational reasoning behind production Solana programs before deployment machinery is added.</p><a href="https://github.com/stawuah/rssol-memory/tree/main/protocol-core" target="_blank" rel="noreferrer">View Protocol Core <Arrow /></a></div><div className="track-content"><div className="study-note"><b>Non-negotiable loop</b><span>Read the exercise README, explain the invariant, predict every test, implement one <code>todo!()</code>, then add the adversarial test.</span></div><ol>{protocol.map((item, index) => <li key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span><i>↘</i></li>)}</ol><aside><strong>The production question</strong><p>How do fixed-point math, rounding direction, oracle freshness and state sequencing affect whether a financial protocol remains solvent and safe?</p></aside></div></div></section>
    <section className="course-close"><div className="wrap"><div><Eyebrow tone="light">A course with receipts</Eyebrow><h2>Do not race<br />the exercises.</h2></div><div><p>Every track rewards explanation, tests and deterministic fixes over copied answers. Finish with an artifact you can inspect, defend and build upon.</p><Button variant="lime" asChild><a href="https://github.com/stawuah/rssol-memory/blob/main/README.md" target="_blank" rel="noreferrer">Read the full curriculum <Arrow /></a></Button></div></div></section></main>
}

function TeamApplication() {
  const [sent, setSent] = useState(false)
  return <form className="team-application" onSubmit={(event) => { event.preventDefault(); setSent(true) }}>
    <div className="form-field"><label htmlFor="team-name">Your name</label><input id="team-name" required placeholder="Full name" /></div>
    <div className="form-field"><label htmlFor="team-email">Email</label><input id="team-email" required type="email" placeholder="you@example.com" /></div>
    <div className="form-field form-field-wide"><label htmlFor="team-choice">Preferred team</label><select id="team-choice" required defaultValue=""><option value="" disabled>Choose a team</option><option>Validators</option><option>Stablecoin Sandbox</option><option>Agentic Payments</option><option>Mobile & Consumer</option></select></div>
    <div className="form-field form-field-wide"><label htmlFor="team-proof">What are you ready to contribute?</label><textarea id="team-proof" required rows="4" placeholder="Share your skills, a project, or the first milestone you would take on." /></div>
    <Button type="submit">{sent ? 'Application received' : 'Apply to a team'} <Arrow /></Button>
    <small>{sent ? 'Thanks. Shortlisted builders will be invited to an interview round before team placement.' : 'Selection is followed by an interview to understand readiness, fit, and commitment.'}</small>
  </form>
}

function Security() {
  const teams = [
    ['01', 'Validators', 'The foundation', 'Run a six-week Validator School covering node setup, security, monitoring, incident response, and operations.', ['Hands-on access to a shared testnet/devnet validator', 'Path into the Solana Foundation Delegation Program (SFDP)', 'Validator-track resume line and referral network'], [['Agave validator setup guide', 'https://docs.anza.xyz/operations/guides/validator-start'], ['SFDP FAQ', 'https://solana.org/faq'], ['Validator Guidebook', 'https://github.com/solana-validators/solana-validator-guidebook']]],
    ['02', 'Stablecoin Sandbox', 'The rails', 'Experiment with issuance, settlement, Token-2022 transfer hooks, confidential transfers, and PYUSD / USDC flows.', ['Shared sandbox with test tokens, faucet access, and devnet infra', 'Mentorship from ChainPay / Token-2022 build experience', 'A credible demo project for grant applications'], [['Token-2022 examples', 'https://solana.com/docs/programs/examples'], ['Confidential transfers skill', 'https://solana.com/skills'], ['Solana Foundation grants', 'https://solana.com/grants']]],
    ['03', 'Agentic Payments', 'The frontier', 'Build on x402 and MCP tooling for agents that can pay each other, with human-approved and delegated-wallet modes.', ['Direct access to ChainPay architecture as a working reference', 'Up to $7 AI credit for experiments', 'Visibility for Colosseum and hackathon submissions'], [['Solana x402 overview', 'https://solana.com/x402'], ['x402 getting started', 'https://solana.com/developers/guides/getstarted/intro-to-x402'], ['Network and token support', 'https://docs.x402.org/core-concepts/network-and-token-support']]],
    ['04', 'Mobile & Consumer', 'The face', 'Ship usable Solana apps for Ghana and beyond, with access to Solana Mobile / Seeker and a path toward App Store and Play Store distribution.', ['Ghana Solana Community dApp Store / Publisher account', 'Priority Seeker testing track and direct dApp Store distribution', 'Zero commission on dApp Store distribution'], [['Publisher portal', 'https://publish.solanamobile.com'], ['dApp Store developer docs', 'https://docs.solanamobile.com/solana-mobile-stack/dapp-store'], ['Mobile builder grants', 'https://solanamobile.com/developers']]],
  ]
  return <main className="teams-page"><section className="teams-hero wrap"><AdinkraSymbol kind="sankofa" label="Sankofa symbol" /><div><Eyebrow>Community super team</Eyebrow><h1>Four teams.<br /><em>One stack.</em></h1><p>Specialists build independently, then plug into each other: validators underwrite the rails, the sandbox settles agents, and mobile makes the work useful.</p><div className="team-stack-nav"><a href="#validators">Validators</a><a href="#stablecoin-sandbox">Sandbox</a><a href="#agentic-payments">Agentic</a><a href="#mobile-consumer">Mobile</a></div></div><div className="stack-visual" aria-label="Team stack"><span>Mobile & Consumer</span><span>Agentic Payments</span><span>Stablecoin Sandbox</span><span>Validators</span></div></section>
    <section className="team-grid wrap">{teams.map(([n, title, kicker, desc, benefits, resources]) => <article id={title.toLowerCase().replaceAll(' & ', '-').replaceAll(' ', '-')} key={title}><div className="team-card-top"><b>{n}</b><Eyebrow>{kicker}</Eyebrow></div><h2>{title}</h2><p>{desc}</p><strong className="team-benefit-label">What members get</strong><ul>{benefits.map((item) => <li key={item}>{item}</li>)}</ul><div className="team-resources"><b>Reference links</b>{resources.map(([label, href]) => <a key={label} href={href} target="_blank" rel="noreferrer">{label} <Arrow /></a>)}</div><a href="#apply">Join this team <Arrow /></a></article>)}</section>
    <section className="teams-benefits"><div className="wrap"><Eyebrow>What you unlock</Eyebrow><h2>Opportunity follows<br /><em>contribution.</em></h2><div className="benefit-strip"><span>Mobile builders <b>Solana Seeker + app distribution</b></span><span>AI builders <b>$7 AI credit for experiments</b></span><span>Sandbox builders <b>Token-2022 and stablecoin lab access</b></span><span>Validator builders <b>Six-week Validator School</b></span></div></div></section>
    <section className="team-process wrap"><div><Eyebrow>How selection works</Eyebrow><h2>Ready is<br /><em>demonstrated.</em></h2></div><ol><li><b>01</b><span>Choose the team where your skills and curiosity have the clearest fit.</span></li><li><b>02</b><span>Submit the short application with one concrete contribution you can own.</span></li><li><b>03</b><span>Shortlisted builders join an interview round to show readiness and working style.</span></li><li><b>04</b><span>Team leads align you to a milestone and the next shared demo day.</span></li></ol></section>
    <section className="team-apply" id="apply"><div className="wrap"><div><Eyebrow tone="light">Join the stack</Eyebrow><h2>Pick a lane.<br /><em>Bring proof.</em></h2><p>Applications are reviewed by the organizing circle. Team placement is confirmed after the interview round.</p></div><TeamApplication /></div></section></main>
}

function Events() {
  const events = [['01','Akwaaba Genesis Meetup','Meet the vision, recruit founding members and introduce the first Campus Ambassador path.','Introduction · Community'],['02','Faucet & Wallet Build Night','Build or improve a shared onboarding tool: the UI, bot, verification, anti-abuse or analytics.','Workshop · Contribution'],['03','Africa Solana Speed Test','Run measurement tooling from different connections and locations to produce a public Ghana dataset.','Research · Public good']]
  return <main className="events-page"><section className="events-hero wrap"><AdinkraSymbol kind="gye-nyame" label="Gye Nyame symbol" /><Eyebrow>Q1 programme</Eyebrow><h1>Meet.<br />Make.<br /><em>Show it.</em></h1><p>A lean, repeatable structure with one purpose: turn attendees into contributors.</p><div className="programme-flow"><span>Meetup</span><i>→</i><span>Workshop</span><i>→</i><span>Build sprint</span><i>→</i><span>Demo</span></div></section><section className="event-timeline wrap">{events.map(([n,t,d,type], i) => <article key={n}><div className="event-dot"><b>{n}</b></div><div className="event-main"><Eyebrow>{type}</Eyebrow><h2>{t}</h2><p>{d}</p><Link href="/community">Raise your hand <Arrow /></Link></div><div className="event-art"><span>{i === 0 ? 'AKWAABA' : i === 1 ? 'MAKE' : 'MEASURE'}</span></div></article>)}</section><section className="future-event"><div className="wrap"><Eyebrow>Future phase · funding dependent</Eyebrow><h2>Validator School Ghana</h2><p>A six-week practical cohort in architecture, monitoring, server security, incident response and public postmortems—not a one-day talk.</p><span className="future-tag">Not committed to a timeline</span><Link className="future-event-link" href="/security#validators">Explore the Validators team <Arrow /></Link></div></section><section className="events-join"><h2>Be there before<br />it gets loud.</h2><Signup tone="light" /></section></main>
}

function AmbassadorForm() {
  const [sent, setSent] = useState(false)
  return <form className="ambassador-form" onSubmit={(event) => { event.preventDefault(); setSent(true) }}>
    <div className="form-field"><label htmlFor="ambassador-name">Your name</label><input id="ambassador-name" name="name" required autoComplete="name" placeholder="Your full name" /></div>
    <div className="form-field"><label htmlFor="ambassador-email">Email address</label><input id="ambassador-email" name="email" required type="email" autoComplete="email" placeholder="you@example.com" /></div>
    <div className="form-field"><label htmlFor="ambassador-university">University</label><input id="ambassador-university" name="university" required placeholder="Your university" /></div>
    <div className="form-field"><label htmlFor="ambassador-github">GitHub or portfolio</label><input id="ambassador-github" name="github" placeholder="https://github.com/your-name" /></div>
    <div className="form-field form-field-wide"><label htmlFor="ambassador-plan">What would you build on campus?</label><textarea id="ambassador-plan" name="plan" required rows="4" placeholder="A workshop, club, build night, or another useful first move." /></div>
    <Button type="submit">{sent ? 'Interest noted' : 'Join the founding programme'} <Arrow /></Button>
    <small>{sent ? 'Thanks. This application interface is ready; connect a form inbox before applications are reviewed.' : 'Founding applications are reviewed manually. We will only use these details for programme follow-up.'}</small>
  </form>
}

function Ambassadors() {
  const benefits = [
    ['Founding Ambassador status', 'Be publicly credited as a Founding Ambassador across Solana Ghana reports and communications.'],
    ['Official Discord role', 'A direct line to the core team and the broader Solana Ghana community.'],
    ['Starter curriculum pack', 'The rssol-memory Rust-to-Solana curriculum, presentation material, and workshop templates ready for campus.'],
    ['Chartered Solana club', 'Support to formally register a Solana club at your university within the Solana Ghana network.'],
    ['Priority mentorship', '1:1 sessions with the core team and ecosystem builders as the programme grows.'],
    ['Real builder experience', 'Run workshops, build nights, and events that belong on your GitHub and CV.'],
    ['Colosseum builder network', 'Connection to the global Solana builder community through Colosseum’s directory.'],
    ['Devnet tools and RPC access', 'Covered RPC endpoint costs so you and your students are not blocked during build nights.'],
  ]
  return <main className="ambassadors-page"><section className="ambassadors-hero wrap"><div><Eyebrow>Founding Ambassador Programme</Eyebrow><h1>Start a Solana<br /><em>room of your own.</em></h1><p>Bring useful Solana learning, real builder practice, and a durable community to your university.</p></div><div className="ambassador-orbit" aria-hidden="true"><span>Campus</span><i>SG</i><span>Network</span></div></section><section className="ambassador-benefits wrap"><div className="benefit-intro"><Eyebrow>What you receive</Eyebrow><h2>More than a title.</h2><p>Founding Ambassadors get the tools, access, and public credit to make a real contribution on campus.</p></div><div className="benefit-grid">{benefits.map(([title, detail], index) => <article key={title}><b>{String(index + 1).padStart(2, '0')}</b><h3>{title}</h3><p>{detail}</p></article>)}</div></section><section className="ambassador-apply"><div className="wrap"><div><Eyebrow tone="light">Become an ambassador</Eyebrow><h2>Make the first<br />useful move.</h2><p>You do not need to arrive with a finished club. You need the intent to convene, learn in public, and help other builders ship.</p></div><AmbassadorForm /></div></section></main>
}

function Bounties() {
  const groups = [
    ['Active bounties', 'Open opportunities will appear here when verified. We will not invent rewards, deadlines, or ecosystem partnerships.', 'No active bounties published yet.'],
    ['Community bounties', 'Tasks created by Solana Ghana or local builders for useful, reviewable public work.', 'Community bounty board is being prepared.'],
    ['Past bounties', 'Completed work, public receipts, and credited winners.', 'No completed bounties yet.'],
  ]
  return <main className="bounties-page"><section className="bounties-hero wrap"><Eyebrow>Builder opportunities</Eyebrow><h1>Earn by making<br /><em>useful things.</em></h1><p>A single, honest place for Ghanaian builders to find ecosystem work, contribute visibly, and earn when verified opportunities are available.</p><div className="bounty-actions"><a href="#submit-bounty">Submit a bounty <Arrow /></a><a href="#submit-work">Submit your work <Arrow /></a></div></section><section className="bounty-groups wrap">{groups.map(([title, intro, empty]) => <article key={title}><Eyebrow>{title}</Eyebrow><h2>{title}</h2><p>{intro}</p><div className="bounty-empty"><strong>{empty}</strong><span>Every published card will show reward, deadline, difficulty, skills, and a clear apply or submit action.</span></div></article>)}</section><section className="bounty-submit" id="submit-bounty"><div className="wrap"><div><Eyebrow>Post an opportunity</Eyebrow><h2>Have work that needs a builder?</h2><p>Bring a specific outcome, reward, deadline, and review path. We will only list bounties that give builders clear terms.</p></div><Link href="/community" className="text-link">Contact the community team <Arrow /></Link></div></section><section className="work-submit wrap" id="submit-work"><Eyebrow>Builder receipts</Eyebrow><h2>Completed a bounty?</h2><p>Submission will collect a GitHub link, demo, pull request, and the bounty reference once the first verified opportunity is live.</p></section></main>
}

function Hubs() {
  const learning = ['Beginner', 'Rust', 'Anchor', 'Frontend', 'Solana programs', 'DeFi', 'AI × Solana', 'Agentic payments']
  const opportunities = ['Grants', 'Hackathons', 'Bounties', 'Jobs', 'Fellowships', 'Ambassador programs']
  return <main className="hubs-page"><section className="hubs-hero wrap"><Eyebrow>Resource directories</Eyebrow><h1>Find the next<br /><em>useful path.</em></h1><p>Two practical hubs for Ghanaian builders: one for learning the work, one for finding the opportunities that follow it.</p></section><section className="hub-section wrap"><div><Eyebrow>Learning Hub</Eyebrow><h2>Learn by<br />building.</h2><p>Resources will be organised around the skills that let a new builder become useful quickly.</p></div><div className="hub-list">{learning.map((item, index) => <Link href="/learn" key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span><Arrow /></Link>)}</div></section><section className="hub-section opportunities wrap"><div><Eyebrow>Opportunities Hub</Eyebrow><h2>Turn skill into<br />a next step.</h2><p>Verified calls and pathways will be added as they are confirmed—without inflated claims or stale listings.</p></div><div className="hub-list">{opportunities.map((item, index) => <Link href={item === 'Bounties' ? '/bounties' : item === 'Ambassador programs' ? '/ambassadors' : '/community'} key={item}><b>{String(index + 1).padStart(2, '0')}</b><span>{item}</span><Arrow /></Link>)}</div></section></main>
}

function Community() {
  return <main className="community-page"><section className="community-hero wrap"><div><Eyebrow>Four people, one starting point</Eyebrow><h1>A local signal<br />with <em>global reach.</em></h1><p>We are building independently and deliberately: a durable place for Ghanaian builders to find each other and the wider Solana ecosystem.</p></div><div className="community-logo"><img src="/solana_ghana.jpeg" alt="Solana Ghana Community mark" /><span>BUILD · CONNECT · EMPOWER</span></div></section><section className="team-wrap"><div className="wrap"><Eyebrow>The founding circle</Eyebrow><h2>Start with<br />who is here.</h2><div className="team-orbit"><svg viewBox="0 0 1000 280" preserveAspectRatio="none" aria-hidden="true"><path d="M0,160 C180,20 340,280 510,135 S770,5 1000,155" /></svg>{[['KA','Kwasi Awuah','Outreach + technical mentorship'],['BR','BR1ANTT_','Community'],['+','Founding role','To be confirmed'],['+','Founding role','To be confirmed']].map(([initial,name,role], i) => <article key={i}><div className={`person p${i}`}>{initial}</div><h3>{name}</h3><p>{role}</p></article>)}</div></div></section><section className="join-grid wrap" id="join"><div><Eyebrow>Find the channel</Eyebrow><h2>The room is<br />taking shape.</h2><p>Choose a channel. We’ll share the earliest event and build information with the founding community first.</p></div><div className="channels"><a href="https://t.me/solanaghanacommunity" target="_blank" rel="noreferrer"><b>Telegram</b><span>For the quick signal <Arrow /></span></a><a href="https://chat.whatsapp.com/JTaWqtd3YK78ZMHhChc9Z5?mode=gi_t" target="_blank" rel="noreferrer"><b>WhatsApp</b><span>For the community room <Arrow /></span></a><a href="#join"><b>GitHub</b><span>For the work itself <Arrow /></span></a></div></section><section className="community-statement"><div><Eyebrow tone="light">Where this points</Eyebrow><h2>Superteam Ghana is an outcome we build toward—not a title we borrow.</h2><p>Independent community initiative. Official recognition and representation will follow written authorization.</p></div><Signup /></section></main>
}

export function CommunitySite({ page }) {
  const [open, setOpen] = useState(false)
  const pages = { home: <Home />, learn: <Learn />, courses: <Courses />, build: <Build />, ambassadors: <Ambassadors />, security: <Security />, events: <Events />, community: <Community /> }
  return <div className={`site ${pageTheme[page]}`}><Header page={page} open={open} setOpen={setOpen} />{pages[page]}<Footer /></div>
}
